image: glassfish

services:
  - mysql

variables:
  MYSQL_DATABASE: phaseten
  MYSQL_ROOT_PASSWORD: root

build:
  script:
    - echo "AS_ADMIN_PASSWORD=${ADMIN_PASSWORD}" > /tmp/glassfishpwd
    - wget "http://central.maven.org/maven2/mysql/mysql-connector-java/5.1.45/mysql-connector-java-5.1.45.jar" -P "/usr/local/glassfish4/glassfish/domains/domain1/lib/ext/"
    - asadmin start-domain
    - mv PhaseTen-ear/glassfish-resources-ci.xml PhaseTen-ear/EarContent/META-INF/glassfish-resources.xml
    - ./gradlew clean ear
    - asadmin -u "admin" --passwordfile /tmp/glassfishpwd --interactive=false deploy --force=true PhaseTen-ear/build/libs/PhaseTen-ear.ear
    - ./gradlew build
  tags:
    - docker
  artifacts:
    paths:
    - PhaseTen-client/build/libs/
    - PhaseTen-client/build/reports/
    - PhaseTen-common/build/libs/
    - PhaseTen-common/build/reports/
    - PhaseTen-ear/build/libs/
    - PhaseTen-ear/build/reports/
    - PhaseTen-ejb/build/libs/
    - PhaseTen-ejb/build/reports/
    - PhaseTen-gui/build/libs/
    - PhaseTen-gui/build/reports/
    expire_in: 1 week
